steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/vanitya-backend", "."]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy vanitya-backend \
          --image gcr.io/$PROJECT_ID/vanitya-backend \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars \
            DJANGO_SUPERUSER_USERNAME=vanitya,\
            DJANGO_SUPERUSER_PASSWORD=Vanitya@1234,\
            DJANGO_SUPERUSER_EMAIL=vanitya18@gmail.com,\
            DATABASE_URL=postgres://postgres:Vanitya%401234@34.60.243.200:5432/vanitya-postgres,\
            SECRET_KEY=django-insecure-xm43@91+9jv1@=x5&2u8@v0@9dp3ej0r%a8v#wue7!91^7%5l+,\
            DEBUG=False

images:
  - gcr.io/$PROJECT_ID/vanitya-backend
