steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/vanitya-backend", "."]

  # Step 2: Run migrations using the built Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "run",
        "--rm",
        "--env",
        "DATABASE_URL=${_DATABASE_URL}",
        "--env",
        "SECRET_KEY=${_SECRET_KEY}",
        "--env",
        "DEBUG=${_DEBUG}",
        "gcr.io/$PROJECT_ID/vanitya-backend",
        "python",
        "manage.py",
        "migrate",
      ]

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy vanitya-backend \
          --image gcr.io/$PROJECT_ID/vanitya-backend \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars DATABASE_URL=${_DATABASE_URL},SECRET_KEY=${_SECRET_KEY},DEBUG=${_DEBUG}

images:
  - gcr.io/$PROJECT_ID/vanitya-backend
