# Generated by Django 5.1.6 on 2025-04-05 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_language', models.CharField(choices=[('hindi', 'Hindi'), ('telugu', 'Telugu'), ('tamil', 'Tamil'), ('english', 'English')], max_length=20)),
                ('learning_language', models.CharField(choices=[('hindi', 'Hindi'), ('telugu', 'Telugu'), ('tamil', 'Tamil'), ('english', 'English')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'known_language', 'learning_language')},
            },
        ),
    ]
