# Generated by Django 5.1.6 on 2025-04-05 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_languagepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagepreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
