# Generated by Django 5.1.6 on 2025-04-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_languagepreference_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagepreference',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Fluent', 'Fluent'), ('Native', 'Native')], default='Beginner', max_length=20),
        ),
    ]
