# Generated by Django 5.1.6 on 2025-04-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_languagepreference_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagepreference',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
    ]
